server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "64276881262eb22b574cebf997ea3bcbea7d1adfe9c5b355ad7eb3945eece834"